name: TestAndBuild

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  npm_config_cache: "/usr/local/npm-cache"
  YARN_CACHE_FOLDER: "/usr/local/npm-cache"

jobs:
  melwallet-js-test:
      runs-on: self-hosted

      container:
        image: node:latest
        volumes:
          - /var/lib/docker:/var/lib/docker
          - /usr/local/npm-cache:/usr/local/npm-cache

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Run Yarn Install
          run: yarn install --prefer-offline

        - name: Run NPM Test
          run: npm test

  ginkou-build:
    runs-on: self-hosted

    container:
      image: node:latest
      volumes:
        - /var/lib/docker:/var/lib/docker
        - /usr/local/npm-cache:/usr/local/npm-cache

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Yarn Install
        run: yarn install --prefer-offline

      - name: Run NPM Build
        env:
          BUILD: "development"
        run: npm run build
